config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :images
  get 'probar', to: 'control#saludo'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
    mount_uploader :picture, PictureUploader

    validates :description, presence: true

    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :configure_devise_params, if: :devise_controller?

    def configure_devise_params
        devise_parameter_sanitizer.permit(:sign_up) do |user|
          user.permit(:name, :email, :password, :password_confirmation)
        end
    end
end

app/controllers/control_controller.rb
class ControlController < ApplicationController
    def saludo
        @name = 'Enmanuel'
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      @images = Image.paginate(page: params[:page], per_page: 6)
                     .order(id: :desc)
                     .where user_id: current_user.id
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
    before_action :set_image, only: [:show, :edit, :update, :destroy]
    def index
        @images = Image.where user_id: current_user.id
    end
    def new
        @image = Image.new
    end

    def create
      @image = current_user.images.new image_params

      if @image.save
        return redirect_to images_path
      end

      render :new
    end

    def show
    end

    def edit
    end

    def update
        @image.update image_params
        redirect_to @image
    end

    def destroy
        @image.destroy
        redirect_to images_path
    end
    private
    def image_params
        params.require(:image).permit :description, :picture
    end

    def set_image
        @image = Image.find params[:id]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/control_helper.rb
module ControlHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/control/saludo.html.erb
<p>hola <%= @name %> desde el controlador</p>

app/views/home/index.html.erb
<% if user_signed_in? %>
  <div class="row">

    <div class="col-4">

    </div>

    <div class="col-8">
    <h1><%= current_user.name.upcase %></h1>
     <div>
      <ul class="nav">
        <li class="margin-right">
          <p><strong><%= @images.count %></strong> publicaciones </p>
        </li>
        <li class="margin-right">
          <p><strong>300</strong> seguidores </p>
        </li>
        <li class="margin-right">
          <p><strong>5</strong> seguidos </p>
        </li>
      </ul>
      </div>
    </div>

  </div>

  <div class='row'>
        <%= render @images %>
  </div>

<div class="nav">
  <%= will_paginate @images %>
</div>
<% else %>
  <h1>COMMUNITY</h1>
<% end %>

app/views/images/_form.html.erb
  <div class="form-group">
    <%= form_for @image, builder: CustomFormBuilder do |f|%>
      <%= f.form_error %>
      <%= f.label :description %><br>
      <%= f.text_field :description, class: 'form-control' %>
      <%= f.field_error :description %>
      <br>
      <%= f.label :picture %><br>
      <%= f.file_field :picture %>
      <%= f.submit 'Enviar', class: 'btn btn-primary'%>
    <% end %>
  </div>

app/views/images/_image.html.erb
<div class="col-4">
  <figure class="figure">
    <!-- <img src="https://getuikit.com/v2/docs/images/placeholder_600x400.svg" class="figure-img img-fluid rounded"> -->
    <%= image_tag image.picture.thumb.url, class: 'figure-img img-fluid rounded' %>
    <figcaption class="figure-caption"><%= image.description%>
    <%= link_to t('.edit_link'), edit_image_path(image), class: "btn btn-outline-success" %>
    <%= link_to t('.remove_link'), image, method: :delete, data: {confirm: 'estas seguro?'}, class: "btn btn-outline-danger" %></figcaption>
  </figure>
</div>

app/views/images/edit.html.erb
<div class="container">
<div class="col-4">
  <h2> editar imagen</h2>
  <%= render 'form' %>
</div>
</div>

app/views/images/index.html.erb
<div class="container">
    <div class='row'>
        <%= render @images %>
    </div>
</div>

app/views/images/new.html.erb
<div class="container">
  <div class="col-4">
    <h2> nueva imagen</h2>
    <%= render 'form' %>
  </div>
</div>  

app/views/images/show.html.erb
 <%= image_tag @image.picture.thumb.url, class: 'figure-img img-fluid rounded' %>
<%= @image.description %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Community</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <ul class='nav justify-content-end'>
    <%- if user_signed_in? %>
     <li class='nav-item'><%= link_to ' Salir ', destroy_user_session_path, method: :delete, class: 'nav-link btn btn-danger' %></li>
     <% else %>
      <li class='nav-item'> <%= link_to ' Iniciar ', new_user_session_path, class: 'nav-link' %></li>
      <li class='nav-item'> <%= link_to ' Registrarme ', new_user_registration_path, class: 'nav-link' %></li>
    <% end %>
  </ul>

  <div class='container'>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </div>
  </body>
</html>